SELECT * FROM public."user";
SELECT * FROM public."role";
SELECT * FROM public."acl";
SELECT * FROM public."accesstoken";
SELECT * FROM public."rolemapping";
SELECT * FROM ecommerce."customer";
SELECT * FROM ecommerce."order";
SELECT * FROM ecommerce."product";
SELECT * FROM ecommerce."stored_product";
